--- 
title: "'Growing' of ggplot2 and plotly"
author: "Yuchen Meng, Yujie Tu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Nowadays, plots are popular among all fields because of its conciseness and clearness. R is famous as a powerful tool of making nice plots. Among various R graphical packages, ggplot2 and plotly are two well-known and common tools. But they have different graphing philosophy and in consequence have different syntax and features. 

[ggplot2](https://ggplot2.tidyverse.org/) is an open-source data visualization package and an implementation of [A Layered Grammar of Graphics](https://vita.had.co.nz/papers/layered-grammar.pdf), which enables us to concisely describe the components of a graphic. It ggplot2 allows users to incorporate various forms of complexity to their visualizations without additional hassle, and remove them with ease if necessary.   

While [plotly](https://plotly.com/r/) is also an open-source package designed by a technical computing company and gains popularity over past years though it is younger than ggplot2. It has simple syntax and is compatible with many languages. Plotly’s visualization library offers users enhanced interactivity features, such as the ability to interact with graphs on display.

Both [ggplot2](https://github.com/tidyverse/ggplot2) and [plotly](https://github.com/plotly/plotly.R) uses GitHub for version control and code management. And we would like to see and compare the development of these two packages through data crawled from GitHub REST API. Specifically, we will crawl commits of main branch, issues, and pull requests for both packages. And the problems we have are:  

1) The quantity pattern of pull requests, issues and commits for these two packages during time.  
2) The solving pattern of pull requests and issues for these two packages.  
3) Whether the pandemic has an impact on the development of these two packages.  

Here is a little bit detail on how GitHub works: usually, a project on GitHub will have a handful of key developers to develop and maintain. But there can be a whole community of users help this process. They can report problems by submitting an [issue](https://docs.github.com/en/issues), they can help change the source code (fix a bug, add a new feature, and etc.) by submitting a [pull request](https://docs.github.com/en/pull-requests), and all users need to [commit](https://docs.github.com/en/pull-requests/committing-changes-to-your-project) their local changes to GitHub so that their modification can be seen online by other users. Of course, we omit tons of details in this short summary, you can learn about all the details about how GitHub works [here](https://docs.github.com/en/get-started) 
